(format t "WZL自动记账系统2.0（开源）~%利用规约：先要init-debt启动。欠债为负，还债为正~%funs debt欠债、read-debt查询、list-debt全部、sum-debt求和、save-debt保存")
(defvar *db* nil)
(defun prompt-read (prompt)(format *query-io* "~a: " prompt)(force-output *query-io*)(read-line *query-io*))
(defun save-debt ()
(with-open-file (out "./debt.txt" :direction :output :if-exists :supersede)(with-standard-io-syntax (print *db* out))))
(defun init-debt ()
(with-open-file (in "./debt.txt" )(with-standard-io-syntax (setf *db* (read in)))))
(defun debt (name &rest moneys)
 (dolist (money moneys)
(if (typep money 'number )
 (push (cons name (rationalize money)) *db*)
(format t "操作失败")))(format t "操作成功，记得save-debt保存！"))
(defun read-debt (name)
(remove-if-not #'(lambda 
(x) (equal (car x) name )) *db*))

(defun sum-debt (name)
(let ((x  (apply #'+ (mapcar #'cdr (read-debt name)))))
(list name x (float x))))
(defun list-debt ()
(let ((db nil))
(mapc #'(lambda (x)(let ((obj (car x)))
(if (member obj db) nil (push obj db)))) *db*)
(mapcar #'sum-debt db)))
(defun all-debts ()
(apply #'+ (mapcar #'cdr *db*)))
